version: "3.8"

services:
  db-postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PORT: ${DB_PORT}
    env_file:
      - ./env/db.env
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-ngen:
    depends_on:
      - db-postgres
    volumes:
      - ./tests:/app/tests
volumes:
  postgres-data:
