version: "3.8"

services:
  db-postgres:
    image: postgres:13.1
    restart: always
    environment:
      POSTGRES_HOST: ${SOURCE_DB_HOST}
      POSTGRES_PORT: ${SOURCE_DB_PORT}
      POSTGRES_USER: ${SOURCE_DB_USER}
      POSTGRES_PASSWORD: ${SOURCE_DB_PASSWORD}
      POSTGRES_DB: ${SOURCE_DB_DATABASE}
    env_file:
      - ./env/db.env
    ports:
      - ${SOURCE_DB_PORT}:${SOURCE_DB_PORT}
    volumes:
      - postgres-data:/var/lib/postgresql/data
  db-ngen:
    depends_on:
      - db-postgres
    volumes:
      - ./tests:/app/tests
volumes:
  postgres-data:
